local settings = {
        partyList = {
            columnWidth =  410 ,
            columns =  1 ,
            rowHeight =  46 ,
            rows =  6 ,
            background = {
                enabled =  true ,
                imgBottom = {
                    color =  '#FFFFFFDD' ,
                    enabled =  true ,
                    path = 'assets/xiv/BgBottom.png' ,
                    pos = {0,0},
                    size = {377,21},
                },
                imgMid = {
                    color =  '#FFFFFFDD' ,
                    enabled =  true ,
                    path = 'assets/xiv/BgMid.png' ,
                    pos = {0,21},
                    size = {377,12},
                },
                imgTop = {
                    color =  '#FFFFFFDD' ,
                    enabled =  true ,
                    path = 'assets/xiv/BgTop.png' ,
                    pos = {0,0},
                    size = {377,21},
                },
                pos = {0,-21},
            },
            listItem = {
                enabled =  true ,
                hp = {
                    bar = {
                        animSpeed =  0.1 ,
                        enabled =  true ,
                        imgBar = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/Bar.png' ,
                            pos = {13,0},
                            size = {102,64},
                        },
                        imgBg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarBG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgFg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarFG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgGlow = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlow.png' ,
                            pos = {13,0},
                            size = {6,64},
                        },
                        imgGlowSides = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlowSides.png' ,
                            pos = {11,0},
                            size = {2,64},
                        },
                        pos = {0,0},
                    },
                    enabled =  true ,
                    hpOrangeColor =  '#F8BA80FF' ,
                    hpRedColor =  '#FC8182FF' ,
                    hpYellowColor =  '#F3F37CFF' ,
                    pos = {19,-7},
                    snapToRaster =  true ,
                    txtValue = {
                        alignRight =  true ,
                        color =  '#F0FFFFFF' ,
                        enabled =  true ,
                        font = 'Grammara',
                        pos = {120,35},
                        size =  11 ,
                        snapToRaster =  true ,
                        stroke =  '#062D54C8' ,
                        strokeWidth =  2 ,
                    },
                    zOrder =  2 ,
                },
                mp = {
                    bar = {
                        animSpeed =  0.1 ,
                        enabled =  true ,
                        imgBar = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/Bar.png' ,
                            pos = {13,0},
                            size = {102,64},
                        },
                        imgBg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarBG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgFg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarFG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgGlow = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlow.png' ,
                            pos = {13,0},
                            size = {6,64},
                        },
                        imgGlowSides = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlowSides.png' ,
                            pos = {11,0},
                            size = {2,64},
                        },
                        pos = {0,0},
                    },
                    enabled =  true ,
                    pos = {150,-7},
                    snapToRaster =  true ,
                    txtValue = {
                        alignRight =  true ,
                        color =  '#F0FFFFFF' ,
                        enabled =  true ,
                        font = 'Grammara',
                        pos = {120,35},
                        size =  11 ,
                        snapToRaster =  true ,
                        stroke =  '#062D54C8' ,
                        strokeWidth =  2 ,
                    },
                    zOrder =  3 ,
                },
                tp = {
                    bar = {
                        animSpeed =  0.1 ,
                        enabled =  true ,
                        imgBar = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/Bar.png' ,
                            pos = {13,0},
                            size = {102,64},
                        },
                        imgBg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarBG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgFg = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarFG.png' ,
                            pos = {0,0},
                            size = {128,64},
                        },
                        imgGlow = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlow.png' ,
                            pos = {13,0},
                            size = {6,64},
                        },
                        imgGlowSides = {
                            color =  '#FFFFFFFF' ,
                            enabled =  true ,
                            path = 'assets/xiv/BarGlowSides.png' ,
                            pos = {11,0},
                            size = {2,64},
                        },
                        pos = {0,0},
                    },
                    enabled =  true ,
                    pos = {281,-7},
                    snapToRaster =  true ,
                    txtValue = {
                        alignRight =  true ,
                        color =  '#F0FFFFFF' ,
                        enabled =  true ,
                        font = 'Grammara',
                        pos = {120,35},
                        size =  11 ,
                        snapToRaster =  true ,
                        stroke =  '#062D54C8' ,
                        strokeWidth =  2 ,
                    },
                    tpFullColor =  '#50B4FAFF' ,
                    zOrder =  4 ,
                },
                jobIcon = {
                    colors = {
                        dd =  '#663535FF' ,
                        healer =  '#3B6529FF' ,
                        special =  '#FF9700FF' ,
                        support =  '#DAB200FF' ,
                        tank =  '#364597FF' ,
                    },
                    enabled =  true ,
                    imgBg = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/jobIcons/bg.png' ,
                        pos = {0,0},
                        size = {36,36},
                    },
                    imgFrame = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/jobIcons/frame.png' ,
                        pos = {0,0},
                        size = {36,36},
                    },
                    imgGradient = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/jobIcons/gradient.png' ,
                        pos = {0,0},
                        size = {36,36},
                    },
                    imgHighlight = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/jobIcons/highlight.png' ,
                        pos = {-13,-13},
                        size = {62,62},
                    },
                    imgIcon = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = '',
                        pos = {0,0},
                        size = {36,36},
                    },
                    path =  'assets/jobIcons/',
                    pos = {-11,-2},
                    scale = {1,1},
                    snapToRaster =  true ,
                    zOrder =  5 ,
                },
                leader = {
                    enabled =  true ,
                    imgAlliance = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/xiv/AllianceLeader.png' ,
                        pos = {0,12},
                        size = {24,24},
                    },
                    imgParty = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/xiv/Leader.png' ,
                        pos = {0,0},
                        size = {24,24},
                    },
                    imgQuarterMaster = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/xiv/QuarterMaster.png' ,
                        pos = {0,24},
                        size = {24,24},
                    },
                    pos = {-24,-8},
                    scale = {1,1},
                    zOrder =  10 ,
                },
                range = {
                    enabled =  true ,
                    imgFar = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/xiv/RangeFar.png' ,
                        pos = {0,0},
                        size = {14,12},
                    },
                    imgNear = {
                        color =  '#FFFFFFFF' ,
                        enabled =  true ,
                        path = 'assets/xiv/Range.png' ,
                        pos = {0,0},
                        size = {14,12},
                    },
                    txtDistance = {
                        color =  '#F0FFFFFF' ,
                        enabled =  true ,
                        font = 'Grammara',
                        pos = {0,1.5},
                        size =  6 ,
                        snapToRaster =  true ,
                        stroke =  '#062D54C8' ,
                        strokeWidth =  1 ,
                    },
                    pos = {30,28.5},
                    zOrder =  11 ,
                },
                hover = {
                    color =  '#FFFFFFAA' ,
                    enabled =  true ,
                    path = 'assets/xiv/Hover.png' ,
                    pos = {20,-8},
                    size = {390,60},
                    zOrder =  0 ,
                },
                cursor = {
                    color =  '#FFFFFFFF' ,
                    enabled =  true ,
                    path = 'assets/xiv/Cursor.png' ,
                    pos = {20,-8},
                    size = {390,60},
                    zOrder =  1 ,
                },
                buffIcons = {
                    alignRight =  false ,
                    color =  '#FFFFFFFF' ,
                    enabled =  true ,
                    numIconsByRow = {19,13},
                    offsetByRow = {0,6},
                    path =  'libs/status/icons/XIView',
                    pos = {293,0},
                    size = {20,20},
                    spacing = {0,1},
                    zOrder =  12 ,
                },
                txtName = {
                    color =  '#F0FFFFFF' ,
                    enabled =  true ,
                    font = 'Arial',
                    pos = {95,1},
                    size =  15 ,
                    snapToRaster =  true ,
                    stroke =  '#062D54C8' ,
                    strokeWidth =  2 ,
                    maxChars =  17 ,
                    zOrder =  6 ,
                },
                txtZone = {
                    alignRight =  false ,
                    color =  '#F0FFFFFF' ,
                    enabled =  true ,
                    font = 'Arial',
                    pos = {292,1},
                    short =  false ,
                    size =  13 ,
                    snapToRaster =  true ,
                    stroke =  '#062D54C8' ,
                    strokeWidth =  2 ,
                    zOrder =  7 ,
                },
                txtJob = {
                    color =  '#F0FFFFFF' ,
                    enabled =  true ,
                    font = 'Arial',
                    pos = {30,0},
                    size =  8 ,
                    snapToRaster =  true ,
                    stroke =  '#062D54C8' ,
                    strokeWidth =  1 ,
                    zOrder =  8 ,
                },
                txtSubJob = {
                    color =  '#F0FFFFFF' ,
                    enabled =  true ,
                    font = 'Arial',
                    pos = {39,9},
                    size =  8 ,
                    snapToRaster =  true ,
                    stroke =  '#062D54C8' ,
                    strokeWidth =  1 ,
                    zOrder =  9 ,
                },
            },
        },
}
return settings;
